import Head from "next/head";
import BlogSection from "../components/BlogSection";
import CTA from "../components/CTA";
import Features from "../components/Features";
import Footer from "../components/Footer";
import Navigation from "../components/Navigation";
import LogoCloud from "../components/LogoCloud";
import ProductSection from "../components/ProductSection";
import ContactCard from "../components/ContactCard";
import Slider from "../components/Slider";
import Partnership from "../components/Partnership";
import Statistics from "../components/Statistics";

import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export default function Home() {
  const { t } = useTranslation("common");
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <Slider width={1000} height={600} />

      {/* <LogoCloud /> */}
      <ProductSection />
      {/* {t("test")} */}
      <Partnership />
      <Statistics />

      {/* <Features /> */}
      <BlogSection />
      {/* <CTA /> */}
      <ContactCard />
      <Footer />
    </div>
  );
}

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common", "footer"])),
  },
});
